server: #服务端口
  port: 18087
spring:
  application:
    name: tanhua-app
  redis:  #redis配置
    port: 6379
    host: 127.0.0.1
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
    timeout: 50000000
    retries: 0

tanhua:
  sms:
    access-key: 
    secret: 
    sign-name: 
    template-code: 
  oss:
    accessKey: 
    secret: 
    endpoint: 
    bucketName: 
    url: 
  aip:
    appId: 
    apiKey: 
    secretKey: 
